# Generated by Django 5.2.9 on 2026-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_price', '0002_replace_buy_sell_with_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='event_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
