# Generated by Django 6.0.2 on 2026-02-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useractivitylog_and_token_version'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='accounts_us_created_643629_idx',
            old_name='accounts_us_created_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='accounts_us_action__9b8bb9_idx',
            old_name='accounts_us_action_idx',
        ),
        migrations.RenameIndex(
            model_name='useractivitylog',
            new_name='accounts_us_user_id_3c3f09_idx',
            old_name='accounts_us_user_idx',
        ),
    ]
