# Generated by Django 6.1 on 2026-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_us_created_idx_accounts_us_created_643629_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='exchange_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=16),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action_type',
            field=models.CharField(choices=[('login_success', 'Login success'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('price_update', 'Price update'), ('bulk_price_update', 'Bulk price update'), ('special_price_update', 'Special price update'), ('template_change', 'Template change'), ('finalize', 'Finalize'), ('impersonate_start', 'Impersonate start'), ('other', 'Other')], max_length=32),
        ),
    ]
