# Generated by Django 6.1 on 2026-08-24 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_collaboration_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Panel user this delegated operator reports to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sub_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('head_operator', 'Head Operator')], default='admin', max_length=24),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
