# Generated by Django 6.1 on 2026-09-05 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_email_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Customer account whose data this user works on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.account'),
        ),
    ]
