# Generated by Django 6.1 on 2026-09-05 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_onboarding_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='action_type',
            field=models.CharField(choices=[('signup', 'Signup'), ('login_success', 'Login success'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('price_update', 'Price update'), ('bulk_price_update', 'Bulk price update'), ('special_price_update', 'Special price update'), ('template_change', 'Template change'), ('finalize', 'Finalize'), ('impersonate_start', 'Impersonate start'), ('other', 'Other')], max_length=32),
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify_email', 'Verify email'), ('login', 'Login')], max_length=32)),
                ('code_hash', models.CharField(max_length=128)),
                ('sent_to', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', '-created_at'], name='accounts_ot_user_id_ff054c_idx')],
            },
        ),
    ]
