# Generated by Django 6.1 on 2026-09-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_useractivitylog_action_type_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_sub',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
