# Generated by Django 6.1 on 2026-09-13 16:16

import accounts.storage
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_customuser_google_sub'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Public path segment. Defaults to the account slug.', max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16)),
                ('layout_slug', models.CharField(default='aurora', max_length=60)),
                ('theme_slug', models.CharField(blank=True, max_length=60)),
                ('theme_overrides', models.JSONField(blank=True, default=dict, help_text='Owner choices layered over the theme: button/card/background style, corner, density, font pair, brand colour.')),
                ('primary_locale', models.CharField(default='en', max_length=8)),
                ('locales', models.JSONField(blank=True, default=list)),
                ('inherit_panel_branding', models.BooleanField(default=True)),
                ('business_name', models.JSONField(blank=True, default=dict)),
                ('tagline', models.JSONField(blank=True, default=dict)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=accounts.storage.AccountUploadPath('website'))),
                ('favicon', models.ImageField(blank=True, null=True, upload_to=accounts.storage.AccountUploadPath('website'))),
                ('seo', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.storage.AccountUploadPath('website'))),
                ('role', models.CharField(choices=[('image', 'Image'), ('logo', 'Logo'), ('hero', 'Hero'), ('gallery', 'Gallery'), ('og', 'Social preview')], default='image', max_length=20)),
                ('alt', models.JSONField(blank=True, default=dict)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='website.websitesite')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=40)),
                ('key', models.CharField(blank=True, default='', max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('variant', models.CharField(blank=True, default='', max_length=60)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.websitesite')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['site', 'order'], name='website_web_site_id_11a987_idx')],
                'unique_together': {('site', 'section_type', 'key')},
            },
        ),
        migrations.CreateModel(
            name='WebsitePublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_publications', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='website.websitesite')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('site', 'version')},
            },
        ),
    ]
