from django.urls import path
from rest_framework.routers import DefaultRouter

from . import api_views

router = DefaultRouter()
router.register("bots", api_views.TelegramBotViewSet, basename="api-telegram-bots")
router.register(
    "channels/manage",
    api_views.TelegramChannelViewSet,
    basename="api-telegram-channels-manage",
)
router.register(
    "auto-post-config",
    api_views.AutoPostConfigViewSet,
    basename="api-telegram-auto-post-config",
)
router.register(
    "customers",
    api_views.CustomerProfileViewSet,
    basename="api-telegram-customers",
)
router.register(
    "exchange-requests",
    api_views.ExchangeRequestViewSet,
    basename="api-telegram-exchange-requests",
)
router.register(
    "price-alerts",
    api_views.PriceAlertViewSet,
    basename="api-telegram-price-alerts",
)

urlpatterns = [
    path(
        "channels/",
        api_views.TelegramChannelListAPIView.as_view(),
        name="api-telegram-channels",
    ),
    path(
        "webhook/<int:bot_id>/",
        api_views.TelegramCustomerWebhookAPIView.as_view(),
        name="api-telegram-customer-webhook",
    ),
    path(
        "send-message/",
        api_views.SendMessageAPIView.as_view(),
        name="api-telegram-send-message",
    ),
    path(
        "default-settings/",
        api_views.DefaultMessageSettingsListAPIView.as_view(),
        name="api-telegram-default-settings-list",
    ),
    path(
        "default-settings/create/",
        api_views.DefaultMessageSettingsCreateAPIView.as_view(),
        name="api-telegram-default-settings-create",
    ),
    path(
        "default-settings/<int:pk>/",
        api_views.DefaultMessageSettingsDetailAPIView.as_view(),
        name="api-telegram-default-settings-detail",
    ),
    path(
        "automation-settings/",
        api_views.AutomationSettingsAPIView.as_view(),
        name="api-telegram-automation-settings",
    ),
    path(
        "admin/verify-bot/",
        api_views.VerifyBotAPIView.as_view(),
        name="api-telegram-admin-verify-bot",
    ),
    path(
        "admin/dashboard/",
        api_views.DashboardAPIView.as_view(),
        name="api-telegram-admin-dashboard",
    ),
    path(
        "admin/reengage/",
        api_views.ReengageAPIView.as_view(),
        name="api-telegram-admin-reengage",
    ),
    path(
        "admin/campaigns/",
        api_views.ReengageCampaignListCreateAPIView.as_view(),
        name="api-telegram-admin-campaigns",
    ),
    path(
        "admin/campaigns/<int:pk>/",
        api_views.ReengageCampaignDetailAPIView.as_view(),
        name="api-telegram-admin-campaign-detail",
    ),
    path(
        "admin/offers/",
        api_views.ReengageOfferListCreateAPIView.as_view(),
        name="api-telegram-admin-offers",
    ),
    path(
        "admin/offers/<int:pk>/",
        api_views.ReengageOfferDetailAPIView.as_view(),
        name="api-telegram-admin-offers-detail",
    ),
    path(
        "admin/snapshots/channel-members/",
        api_views.ChannelMemberSnapshotsAPIView.as_view(),
        name="api-telegram-admin-channel-snapshots",
    ),
] + router.urls
