# Generated by Django 6.1 on 2026-09-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderintake',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('web', 'Web')], max_length=16),
        ),
    ]
