"""Provision and tear down one isolated stack per trial signup (option B).

Nothing here runs unless ``TRIAL_PROVISIONING_ENABLED`` is on, so a developer
machine, CI and any customer-server install stay completely inert: the fleet
records are still written, only the Docker side is skipped. That keeps the
owner panel honest about what it has asked for while the provisioning host is
the only place that actually shells out to Docker.
"""

from __future__ import annotations

import logging
import re
import secrets
import shutil
import subprocess
import tarfile
from datetime import datetime, timezone as dt_timezone
from pathlib import Path

from django.conf import settings
from django.utils import timezone

logger = logging.getLogger(__name__)

COMPOSE_FILENAME = "docker-compose.yml"
ENV_FILENAME = ".env"
_SLUG_CLEAN_RE = re.compile(r"[^a-z0-9]+")
# Traefik router names and DNS labels share this budget; "trial-" eats 6.
MAX_SLUG_LEN = 40
PROVISION_TIMEOUT_SECONDS = 900
TEARDOWN_TIMEOUT_SECONDS = 300


class ProvisioningError(RuntimeError):
    """A compose invocation failed. The caller decides whether to retry."""


class ProvisioningDisabled(RuntimeError):
    """Provisioning was requested on a host that is not the trial host."""


def provisioning_enabled():
    return bool(getattr(settings, "TRIAL_PROVISIONING_ENABLED", False))


def slug_for(user):
    """A DNS- and compose-safe stack name derived from the customer."""
    source = (
        getattr(user, "exchange_name", "")
        or getattr(user, "username", "")
        or f"user{getattr(user, 'pk', '')}"
    )
    cleaned = _SLUG_CLEAN_RE.sub("-", str(source).strip().lower()).strip("-")
    if not cleaned:
        cleaned = f"user{getattr(user, 'pk', '') or ''}"
    base = f"trial-{cleaned}"[:MAX_SLUG_LEN].rstrip("-")
    return base


def unique_slug_for(user):
    """``slug_for`` with a short suffix if that stack name is already taken."""
    from .models import CustomerDeployment

    base = slug_for(user)
    if not CustomerDeployment.objects.filter(slug=base).exists():
        return base
    for _ in range(10):
        suffix = secrets.token_hex(2)
        candidate = f"{base[: MAX_SLUG_LEN - len(suffix) - 1].rstrip('-')}-{suffix}"
        if not CustomerDeployment.objects.filter(slug=candidate).exists():
            return candidate
    raise ProvisioningError(f"could not find a free stack name for {base!r}")


def domain_for(slug):
    return f"{slug}.{settings.TRIAL_BASE_DOMAIN}"


def stack_dir(slug) -> Path:
    return Path(settings.TRIAL_STACKS_ROOT) / slug


def _render_env(deployment) -> str:
    """Per-stack environment. Every secret here is unique to this trial."""
    domain = deployment.domain or domain_for(deployment.slug)
    lines = [
        "# Generated by fleet.provisioning — do not edit by hand.",
        f"# Trial stack for {deployment.customer.username} ({deployment.slug}).",
        "DEPLOYMENT_MODE=customer_server",
        f"DJANGO_SECRET_KEY={secrets.token_urlsafe(50)}",
        "DJANGO_DEBUG=False",
        "DJANGO_USE_HTTP_BEHIND_PROXY=true",
        f"DJANGO_ALLOWED_HOSTS={domain}",
        f"DJANGO_CSRF_TRUSTED_ORIGINS=https://{domain}",
        "SQLITE_PATH=/app/backend/data/db.sqlite3",
        "CELERY_BROKER_URL=redis://redis:6379/0",
        f"DEFAULT_ADMIN_USERNAME={settings.TRIAL_ADMIN_USERNAME}",
        f"DEFAULT_ADMIN_PASSWORD={secrets.token_urlsafe(12)}",
        "DEFAULT_ADMIN_SYNC_PASSWORD=false",
        # The stack reports back to this panel so it appears in the fleet view
        # alongside licensed installs.
        f"FLEET_CHECKIN_URL={settings.FLEET_CHECKIN_URL}",
        f"FLEET_LICENSE_KEY={deployment.license_key}",
        f"TRIAL_SLUG={deployment.slug}",
        f"TRIAL_DOMAIN={domain}",
        f"TRIAL_IMAGE={settings.TRIAL_IMAGE}",
        f"TRIAL_CERT_RESOLVER={settings.TRIAL_CERT_RESOLVER}",
        f"TRIAL_EDGE_NETWORK={settings.TRIAL_EDGE_NETWORK}",
    ]
    return "\n".join(lines) + "\n"


def _write_stack_files(deployment) -> Path:
    target = stack_dir(deployment.slug)
    target.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(settings.TRIAL_COMPOSE_TEMPLATE, target / COMPOSE_FILENAME)
    env_path = target / ENV_FILENAME
    env_path.write_text(_render_env(deployment), encoding="utf-8")
    env_path.chmod(0o600)
    return target


def _compose(deployment, *args, timeout):
    cmd = [
        *settings.DOCKER_COMPOSE_COMMAND,
        "--project-name",
        deployment.slug,
        "--project-directory",
        str(stack_dir(deployment.slug)),
        "--file",
        str(stack_dir(deployment.slug) / COMPOSE_FILENAME),
        *args,
    ]
    logger.info("fleet: running %s", " ".join(cmd))
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if result.returncode != 0:
        raise ProvisioningError(
            f"`{' '.join(args)}` failed for {deployment.slug} "
            f"(exit {result.returncode}): {result.stderr.strip()[:2000]}"
        )
    return result.stdout


def provision(deployment):
    """Bring a trial stack up. Idempotent — ``up -d`` converges an existing one."""
    if not provisioning_enabled():
        raise ProvisioningDisabled(
            "TRIAL_PROVISIONING_ENABLED is off on this host; nothing was provisioned"
        )
    if not deployment.license_key:
        deployment.issue_license()
        deployment.save(update_fields=["license_key"])
    _write_stack_files(deployment)
    _compose(deployment, "up", "--detach", "--remove-orphans", timeout=PROVISION_TIMEOUT_SECONDS)
    deployment.status = deployment.STATUS_ACTIVE
    deployment.provisioned_at = timezone.now()
    deployment.save(update_fields=["status", "provisioned_at"])
    return deployment


def archive(deployment, *, keep_data=True):
    """Stop a trial stack and keep its data, so a late conversion is still possible."""
    if not provisioning_enabled():
        raise ProvisioningDisabled(
            "TRIAL_PROVISIONING_ENABLED is off on this host; nothing was torn down"
        )
    archive_path = None
    if keep_data:
        archive_path = _archive_stack_dir(deployment)
    # `down` without --volumes leaves the SQLite and media volumes in place;
    # a conversion inside the retention window can still copy them across.
    _compose(deployment, "down", "--remove-orphans", timeout=TEARDOWN_TIMEOUT_SECONDS)
    deployment.status = deployment.STATUS_ARCHIVED
    deployment.archived_at = timezone.now()
    if archive_path:
        deployment.notes = (
            f"{deployment.notes}\nArchived {deployment.archived_at:%Y-%m-%d} to {archive_path}"
        ).strip()
        deployment.save(update_fields=["status", "archived_at", "notes"])
    else:
        deployment.save(update_fields=["status", "archived_at"])
    return archive_path


def _archive_stack_dir(deployment) -> str | None:
    source = stack_dir(deployment.slug)
    if not source.is_dir():
        return None
    archive_root = Path(settings.TRIAL_ARCHIVE_ROOT)
    archive_root.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(dt_timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    destination = archive_root / f"{deployment.slug}-{stamp}.tar.gz"
    with tarfile.open(destination, "w:gz") as bundle:
        bundle.add(source, arcname=deployment.slug)
    return str(destination)
