# Generated by Django 5.2.7 on 2025-10-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pricetype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricetype',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pricetype',
            name='source_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='category.currency'),
        ),
        migrations.AddField(
            model_name='pricetype',
            name='target_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='category.currency'),
        ),
        migrations.AddConstraint(
            model_name='pricetype',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_category_pricetype_name'),
        ),
        migrations.AddConstraint(
            model_name='pricetype',
            constraint=models.UniqueConstraint(fields=('category', 'source_currency', 'target_currency', 'trade_type'), name='unique_category_pair_trade'),
        ),
    ]
