# Generated by Django 5.2.7 on 2025-10-22 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_backfill_currency_and_require_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricetype',
            name='unique_category_pair_trade',
        ),
    ]
