# Generated by Django 5.2.7 on 2025-11-25 17:12

from django.db import migrations


def create_default_currencies(apps, schema_editor):
    """
    Create commonly used currencies that are used throughout the website.
    This ensures that these currencies are always available even after database reset.
    """
    Currency = apps.get_model('category', 'Currency')
    
    # List of commonly used currencies in the website
    default_currencies = [
        {'code': 'USD', 'name': 'US Dollar', 'symbol': '$'},
        {'code': 'EUR', 'name': 'Euro', 'symbol': '€'},
        {'code': 'GBP', 'name': 'British Pound', 'symbol': '£'},
        {'code': 'IRR', 'name': 'Iranian Rial', 'symbol': '﷼'},
        {'code': 'IRT', 'name': 'Iranian Toman', 'symbol': 'تومان'},
        {'code': 'USDT', 'name': 'Tether', 'symbol': 'USDT'},
        {'code': 'AED', 'name': 'UAE Dirham', 'symbol': 'د.إ'},
        {'code': 'TRY', 'name': 'Turkish Lira', 'symbol': '₺'},
        {'code': 'CAD', 'name': 'Canadian Dollar', 'symbol': 'C$'},
        {'code': 'AUD', 'name': 'Australian Dollar', 'symbol': 'A$'},
        {'code': 'JPY', 'name': 'Japanese Yen', 'symbol': '¥'},
        {'code': 'CHF', 'name': 'Swiss Franc', 'symbol': 'CHF'},
    ]
    
    # Create currencies if they don't exist
    for currency_data in default_currencies:
        Currency.objects.get_or_create(
            code=currency_data['code'],
            defaults={
                'name': currency_data['name'],
                'symbol': currency_data['symbol']
            }
        )


def reverse_create_default_currencies(apps, schema_editor):
    """
    Reverse migration - optionally remove default currencies.
    We'll leave them in place to avoid breaking existing data.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_pricetype_unique_category_pair_trade'),
    ]

    operations = [
        migrations.RunPython(
            create_default_currencies,
            reverse_create_default_currencies
        ),
    ]
