# Generated by Django 5.2.7 on 2025-11-25 17:12

from django.db import migrations


def create_default_currencies(apps, schema_editor):
    """
    Create commonly used currencies that are used throughout the website.
    This ensures that these currencies are always available even after database reset.
    """
    Currency = apps.get_model('category', 'Currency')
    
    # List of commonly used currencies in the website
    default_currencies = [
        {'code': 'USD', 'name': 'US Dollar', 'symbol': '$'},
        {'code': 'USDT', 'name': 'Tether', 'symbol': 'USDT'},
        {'code': 'BTC', 'name': 'Bitcoin', 'symbol': 'BTC'},
        {'code': 'ETH', 'name': 'Ethereum', 'symbol': 'ETH'},
        {'code': 'BNB', 'name': 'BNB', 'symbol': 'BNB'},
        {'code': 'EUR', 'name': 'Euro', 'symbol': 'EUR'},
        {'code': 'GBP', 'name': 'British Pound', 'symbol': 'GBP'},
        {'code': 'AUD', 'name': 'Australian Dollar', 'symbol': 'AUD'},
        {'code': 'CAD', 'name': 'Canadian Dollar', 'symbol': 'CAD'},
        {'code': 'CHF', 'name': 'Swiss Franc', 'symbol': 'CHF'},
        {'code': 'CNY', 'name': 'Chinese Yuan', 'symbol': 'CNY'},
        {'code': 'TRY', 'name': 'Turkish Lira', 'symbol': 'TRY'},
        {'code': 'IRR', 'name': 'Iranian Rial', 'symbol': 'IRR'},
        {'code': 'IRT', 'name': 'Iranian Toman', 'symbol': 'IRT'},
        {'code': 'AED', 'name': 'UAE Dirham', 'symbol': 'AED'},
        {'code': 'JPY', 'name': 'Japanese Yen', 'symbol': 'JPY'},
        {'code': 'RUB', 'name': 'Russian Ruble', 'symbol': 'RUB'},
        {'code': 'IQD', 'name': 'Iraqi Dinar', 'symbol': 'IQD'},
        {'code': 'XAU', 'name': 'Gold', 'symbol': 'XAU'},
    ]
    
    # Create currencies if they don't exist
    for currency_data in default_currencies:
        Currency.objects.update_or_create(
            code=currency_data['code'],
            defaults={'name': currency_data['name'], 'symbol': currency_data['symbol']}
        )


def reverse_create_default_currencies(apps, schema_editor):
    """
    Reverse migration - optionally remove default currencies.
    We'll leave them in place to avoid breaking existing data.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_pricetype_unique_category_pair_trade'),
    ]

    operations = [
        migrations.RunPython(
            create_default_currencies,
            reverse_create_default_currencies
        ),
    ]
