# Generated by Django 6.0.2 on 2026-03-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_unique_currency_pair_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='inline_buttons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
