# Generated by Django 5.2.7 on 2025-11-04 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A friendly name for this bot', max_length=100, verbose_name='Bot Name')),
                ('token', models.CharField(help_text='Telegram bot token from @BotFather', max_length=200, verbose_name='Bot Token')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bot is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Telegram Bot',
                'verbose_name_plural': 'Telegram Bots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A friendly name for this channel', max_length=100, verbose_name='Channel Name')),
                ('chat_id', models.CharField(help_text='Telegram channel chat ID (e.g., @channelname or -1001234567890)', max_length=50, verbose_name='Chat ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this channel is currently active', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bot', models.ForeignKey(help_text='The bot used to send messages to this channel', on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='telegram_app.telegrambot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Telegram Channels',
                'ordering': ['-created_at'],
                'unique_together': {('bot', 'chat_id')},
            },
        ),
    ]
