# Generated by Django 6.0.2 on 2026-02-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_create_default_currencies'),
        ('special_price', '0001_initial'),
        ('telegram_app', '0003_add_telegram_bot_display_notes_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmessagesettings',
            name='default_buttons',
            field=models.JSONField(blank=True, default=list, help_text='JSON structure describing inline buttons. Example: [{"text": "View", "url": "https://example.com"}]', verbose_name='Default Buttons'),
        ),
        migrations.CreateModel(
            name='AutoPostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.TimeField(help_text='Local time of day when auto-post should run.', verbose_name='Time of Day')),
                ('timezone', models.CharField(default='Asia/Tehran', help_text='IANA timezone name used when interpreting time_of_day.', max_length=64, verbose_name='Time Zone')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this configuration is currently active.', verbose_name='Enabled')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_post_configs', to='category.category', verbose_name='Category')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_post_configs', to='telegram_app.telegramchannel', verbose_name='Channel')),
                ('special_price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_post_configs', to='special_price.specialpricetype', verbose_name='Special Price Type')),
            ],
            options={
                'verbose_name': 'Auto Post Config',
                'verbose_name_plural': 'Auto Post Configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
