# Generated by Django 6.1 on 2026-08-16 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0004_alter_defaultmessagesettings_default_buttons_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_bots', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='token',
            field=models.CharField(help_text='Telegram bot token from @BotFather (encrypted at rest)', max_length=500, verbose_name='Bot Token'),
        ),
    ]
