# Generated by Django 6.0.6 on 2026-06-10 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_remove_unique_currency_pair_trade_constraint'),
        ('telegram_app', '0004_alter_defaultmessagesettings_default_buttons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='default_category',
            field=models.ForeignKey(blank=True, help_text='Category board shown when no currency keyword is matched', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_bots', to='category.category', verbose_name='Default Price Board'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='gateway_enabled',
            field=models.BooleanField(default=False, help_text='Enable inbound auto-reply for customer messages', verbose_name='Gateway Enabled'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='order_button_text',
            field=models.CharField(blank=True, default='🛒 ثبت سفارش سریع', max_length=128, verbose_name='Order Button Text'),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='webhook_secret_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Secret UUID used in inbound webhook URL', verbose_name='Webhook Secret'),
        ),
    ]
