# Generated by Django 6.1 on 2026-08-16 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0005_telegrambot_owner_alter_telegrambot_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text='Telegram user id from updates (unique per customer).', unique=True, verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, default='', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Last Name')),
                ('language', models.CharField(blank=True, default='', help_text='Telegram language_code or preferred language.', max_length=16, verbose_name='Language')),
                ('tag', models.CharField(choices=[('global', 'Global'), ('vip', 'VIP'), ('special', 'Special')], default='global', help_text='Staff-assigned customer tag (global, vip, or special).', max_length=16, verbose_name='Tag')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_currency', models.CharField(help_text='ISO 4217 code.', max_length=8, verbose_name='Source Currency')),
                ('target_currency', models.CharField(help_text='ISO 4217 code.', max_length=8, verbose_name='Target Currency')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Amount')),
                ('price_at_request', models.DecimalField(decimal_places=8, help_text='Customer-typed price at the time of the request.', max_digits=20, verbose_name='Price at Request')),
                ('ttl_minutes', models.PositiveIntegerField(verbose_name='TTL (minutes)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('closed', 'Closed')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requests', to='telegram_app.telegrambot', verbose_name='Bot')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to='telegram_app.customerprofile', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Exchange Request',
                'verbose_name_plural': 'Exchange Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], max_length=16, verbose_name='Direction')),
                ('source_currency', models.CharField(help_text='ISO 4217 code.', max_length=8, verbose_name='Source Currency')),
                ('target_currency', models.CharField(help_text='ISO 4217 code.', max_length=8, verbose_name='Target Currency')),
                ('target_price', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Target Price')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Triggered At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='telegram_app.customerprofile', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Price Alert',
                'verbose_name_plural': 'Price Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, verbose_name='Telegram User ID')),
                ('state', models.CharField(choices=[('START', 'Start'), ('MAIN_MENU', 'Main Menu')], default='START', max_length=64, verbose_name='State')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Opaque FSM draft / scratch data for the conversation.', verbose_name='Context')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to='telegram_app.telegrambot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Bot Session',
                'verbose_name_plural': 'Bot Sessions',
                'ordering': ['-last_activity'],
                'constraints': [models.UniqueConstraint(fields=('telegram_user_id', 'bot'), name='unique_bot_session_per_user_bot')],
            },
        ),
    ]
