# Generated by Django 6.1 on 2026-08-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0006_customer_bot_foundation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsession',
            name='state',
            field=models.CharField(choices=[('START', 'Start'), ('MAIN_MENU', 'Main Menu'), ('PROFILE', 'Profile'), ('EXCHANGE_SOURCE', 'Exchange Source'), ('EXCHANGE_TARGET', 'Exchange Target'), ('EXCHANGE_AMOUNT', 'Exchange Amount'), ('EXCHANGE_PRICE', 'Exchange Price'), ('EXCHANGE_TTL', 'Exchange TTL'), ('EXCHANGE_SUMMARY', 'Exchange Summary'), ('ALERT_MENU', 'Alert Menu'), ('ALERT_SOURCE', 'Alert Source'), ('ALERT_TARGET', 'Alert Target'), ('ALERT_PRICE', 'Alert Price'), ('ALERT_SUMMARY', 'Alert Summary')], default='START', max_length=64, verbose_name='State'),
        ),
    ]
