# Generated by Django 6.1 on 2026-08-16 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0007_bot_session_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='default_exchange_ttl_minutes',
            field=models.PositiveIntegerField(default=5, help_text='TTL applied to new exchange requests from this bot. End-users cannot change it.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Default exchange TTL (minutes)'),
        ),
        migrations.AlterField(
            model_name='exchangerequest',
            name='price_at_request',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Optional historical price; no longer collected from the bot.', max_digits=20, null=True, verbose_name='Price at Request'),
        ),
    ]
