# Generated by Django 6.1 on 2026-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0008_bot_default_ttl_and_nullable_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], db_index=True, default='pending', max_length=16, verbose_name='Status'),
        ),
    ]
