# Generated by Django 6.1 on 2026-08-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0012_botadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopostconfig',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='When the scheduler last dispatched this auto-post (set by Celery beat).', null=True, verbose_name='Last Run At'),
        ),
    ]
