# Generated by Django 6.1 on 2026-09-05 14:03

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0014_telegrambot_account'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='telegrambot',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pricealert',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='telegram_app.telegrambot', verbose_name='Bot'),
        ),
    ]
