# Generated by Django 6.1 on 2026-08-25 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_type', models.CharField(choices=[('trial', 'Trial (our VPS)'), ('customer_server', 'Customer server')], max_length=24)),
                ('slug', models.SlugField(help_text='Stack / container project name; also the trial subdomain label.', max_length=63, unique=True)),
                ('domain', models.CharField(blank=True, default='', max_length=253)),
                ('license_key', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('plan', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('archived', 'Archived'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('installed_version', models.CharField(blank=True, default='', max_length=32)),
                ('last_checkin_at', models.DateTimeField(blank=True, null=True)),
                ('last_checkin_uptime_seconds', models.BigIntegerField(blank=True, null=True)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('renews_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deployment_type', 'status'], name='fleet_custo_deploym_d15bd7_idx'), models.Index(fields=['-last_checkin_at'], name='fleet_custo_last_ch_26efc2_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('license_key__gt', '')), fields=('license_key',), name='fleet_unique_license_key'), models.UniqueConstraint(condition=models.Q(('deployment_type', 'trial'), ('status__in', ('pending', 'provisioning', 'active'))), fields=('customer',), name='fleet_one_live_trial_per_customer')],
            },
        ),
    ]
