# Generated by Django 6.0.6 on 2026-06-10 14:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0012_remove_unique_currency_pair_trade_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('whatsapp_phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('auth_status', models.CharField(choices=[('anonymous', 'Anonymous'), ('verified', 'Verified')], default='anonymous', max_length=16)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Bot Customer',
                'verbose_name_plural': 'Bot Customers',
                'indexes': [models.Index(fields=['platform', 'last_seen_at'], name='bot_gateway_platfor_a4aec1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('telegram_chat_id__isnull', False)), fields=('platform', 'telegram_chat_id'), name='unique_bot_customer_telegram'), models.UniqueConstraint(condition=models.Q(('whatsapp_phone', ''), _negated=True), fields=('platform', 'whatsapp_phone'), name='unique_bot_customer_whatsapp')],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=128)),
                ('phone_number_id', models.CharField(blank=True, max_length=64)),
                ('waba_id', models.CharField(blank=True, max_length=64)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('app_secret_encrypted', models.TextField(blank=True)),
                ('verify_token', models.CharField(blank=True, max_length=128)),
                ('order_button_text', models.CharField(blank=True, default='🛒 ثبت سفارش سریع', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_configs', to='category.category')),
            ],
            options={
                'verbose_name': 'WhatsApp Config',
                'verbose_name_plural': 'WhatsApp Configs',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BotInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=8)),
                ('message_text', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('start', 'Start'), ('price_keyword', 'Price keyword'), ('currency_match', 'Currency match'), ('other', 'Other')], default='other', max_length=32)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('was_rate_limited', models.BooleanField(default=False)),
                ('update_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='bot_gateway.botcustomer')),
            ],
            options={
                'verbose_name': 'Bot Interaction Log',
                'verbose_name_plural': 'Bot Interaction Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='bot_gateway_custome_c7055e_idx')],
            },
        ),
    ]
