# Generated by Django 6.1 on 2026-09-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botcustomer',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('web', 'Web')], max_length=16),
        ),
        migrations.AlterField(
            model_name='botinteractionlog',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('web', 'Web')], max_length=16),
        ),
    ]
