# Generated by Django 6.1 on 2026-09-05 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_customuser_account'),
        ('bot_gateway', '0002_alter_botcustomer_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account'),
        ),
    ]
