# Generated by Django 6.1 on 2026-09-05 18:15

import django.db.models.deletion
from django.db import migrations, models

from accounts.bootstrap import backfill_account


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_customuser_account'),
        ('bot_gateway', '0004_alter_botcustomer_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_account('bot_gateway.BotCustomer'), migrations.RunPython.noop, elidable=True
        ),
        migrations.RunPython(
            backfill_account('bot_gateway.WhatsAppConfig'), migrations.RunPython.noop, elidable=True
        ),
        migrations.AlterField(
            model_name='botcustomer',
            name='account',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='whatsappconfig',
            name='account',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account'),
        ),
    ]
