# Generated by Django 5.2.7 on 2025-11-20 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('source', models.CharField(choices=[('telegram', 'Telegram'), ('finalize', 'Finalize'), ('price_publisher', 'Price Publisher'), ('template_editor', 'Template Editor'), ('system', 'System'), ('other', 'Other')], default='system', max_length=50)),
                ('message', models.TextField(verbose_name='Message')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Additional Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='setting_log_created_e26518_idx'), models.Index(fields=['level', '-created_at'], name='setting_log_level_ab0e3c_idx'), models.Index(fields=['source', '-created_at'], name='setting_log_source_69d75e_idx')],
            },
        ),
    ]
