# Generated by Django 6.0.2 on 2026-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SmartExchange', max_length=100)),
                ('tagline', models.CharField(default='Premium Exchange Panel', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('telegram_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('finalize', 'Finalize'), ('price_publisher', 'Price Publisher'), ('template_editor', 'Template Editor'), ('external_api', 'External API'), ('system', 'System'), ('other', 'Other')], default='system', max_length=50),
        ),
    ]
