# Generated by Django 6.0.2 on 2026-02-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_use_template_editor_for_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='auto_post_on_update',
            field=models.BooleanField(default=False, help_text='If enabled, finalized prices can be auto-posted when updates occur. A scheduler must read this flag and trigger publishing.'),
        ),
    ]
