# Generated by Django 6.0.2 on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0006_sitesettings_auto_post_on_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="base_currency_code",
            field=models.CharField(default="USD", max_length=10),
        ),
    ]
