# Generated by Django 6.1 on 2026-08-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_sitesettings_prices_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_webhook_base_url',
            field=models.URLField(blank=True, default='', help_text='Public HTTPS origin for customer-bot webhooks (e.g. https://panel.example.com). When set, active bots can register /api/telegram/webhook/<bot_id>/ with Telegram.', max_length=500),
        ),
    ]
