# Generated by Django 6.1 on 2026-09-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_sitesettings_site_name_mrexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='use_playwright_for_template_render',
            field=models.BooleanField(default=False, help_text='If enabled, Telegram template boards are rendered via headless Vue screenshot (Playwright). Falls back to Pillow on error.'),
        ),
    ]
