# Generated by Django 6.1 on 2026-09-05 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_customuser_account'),
        ('setting', '0014_sitesettings_use_playwright_for_template_render'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('instagram', 'Instagram'), ('custom', 'Custom')], default='phone', max_length=20)),
                ('label', models.CharField(help_text="Shown to the customer, e.g. 'Sales' or 'Technical support'", max_length=120)),
                ('value', models.CharField(help_text='Phone number, @handle, email address or URL', max_length=255)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome class; falls back to the icon for this kind', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Channel',
                'verbose_name_plural': 'Support Channels',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account'),
        ),
    ]
