# Generated by Django 6.1 on 2026-09-05 18:18

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0016_alter_log_managers_alter_sitesettings_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.storage.AccountUploadPath('branding')),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.storage.AccountUploadPath('branding')),
        ),
    ]
