# Generated by Django 5.2.7 on 2025-11-04 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_remove_pricetype_unique_category_pair_trade'),
        ('change_price', '0002_replace_buy_sell_with_price'),
        ('telegram_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_at', models.DateTimeField(auto_now_add=True, verbose_name='Finalized At')),
                ('message_sent', models.BooleanField(default=False, help_text='Whether the message was successfully sent to Telegram', verbose_name='Message Sent')),
                ('message_text', models.TextField(blank=True, help_text='The message text that was sent to Telegram', null=True, verbose_name='Message Text')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalizations', to='category.category', verbose_name='Category')),
                ('channel', models.ForeignKey(blank=True, help_text='The channel where prices were published', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalizations', to='telegram_app.telegramchannel', verbose_name='Telegram Channel')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalizations', to=settings.AUTH_USER_MODEL, verbose_name='Finalized By')),
            ],
            options={
                'verbose_name': 'Finalization',
                'verbose_name_plural': 'Finalizations',
                'ordering': ['-finalized_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalizedPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalized_prices', to='finalize.finalization', verbose_name='Finalization')),
                ('price_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalizations', to='change_price.pricehistory', verbose_name='Price History')),
            ],
            options={
                'verbose_name': 'Finalized Price History',
                'verbose_name_plural': 'Finalized Price Histories',
            },
        ),
        migrations.AddIndex(
            model_name='finalization',
            index=models.Index(fields=['category', '-finalized_at'], name='finalize_fi_categor_29d20e_idx'),
        ),
        migrations.AddIndex(
            model_name='finalization',
            index=models.Index(fields=['finalized_at'], name='finalize_fi_finaliz_e867e9_idx'),
        ),
        migrations.AddIndex(
            model_name='finalizedpricehistory',
            index=models.Index(fields=['finalization'], name='finalize_fi_finaliz_ce315e_idx'),
        ),
        migrations.AddIndex(
            model_name='finalizedpricehistory',
            index=models.Index(fields=['price_history'], name='finalize_fi_price_h_5b7ff7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='finalizedpricehistory',
            unique_together={('finalization', 'price_history')},
        ),
    ]
