# Generated by Django 5.2.7 on 2025-11-05 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalize', '0001_initial'),
        ('special_price', '0001_initial'),
        ('telegram_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPriceFinalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalized_at', models.DateTimeField(auto_now_add=True, verbose_name='Finalized At')),
                ('message_sent', models.BooleanField(default=False, help_text='Whether the message was successfully sent to Telegram', verbose_name='Message Sent')),
                ('message_text', models.TextField(blank=True, help_text='The message text that was sent to Telegram', null=True, verbose_name='Message Text')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('channel', models.ForeignKey(blank=True, help_text='The channel where price was published', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_price_finalizations', to='telegram_app.telegramchannel', verbose_name='Telegram Channel')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_price_finalizations', to=settings.AUTH_USER_MODEL, verbose_name='Finalized By')),
                ('special_price_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalizations', to='special_price.specialpricehistory', verbose_name='Special Price History')),
            ],
            options={
                'verbose_name': 'Special Price Finalization',
                'verbose_name_plural': 'Special Price Finalizations',
                'ordering': ['-finalized_at'],
                'indexes': [models.Index(fields=['special_price_history', '-finalized_at'], name='finalize_sp_special_d6e33f_idx'), models.Index(fields=['finalized_at'], name='finalize_sp_finaliz_121cab_idx')],
            },
        ),
    ]
