# Generated by Django 5.2.7 on 2025-11-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalize', '0003_image_publication_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalization',
            name='image_caption',
            field=models.TextField(blank=True, help_text='Caption sent alongside the rendered price image.', null=True, verbose_name='Image Caption'),
        ),
        migrations.AlterField(
            model_name='specialpricefinalization',
            name='image_caption',
            field=models.TextField(blank=True, help_text='Caption sent alongside the rendered price image.', null=True, verbose_name='Image Caption'),
        ),
    ]
