# Generated migration for template redesign

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('template_editor', '0001_initial'),
    ]

    operations = [
        # Add new fields to Template
        migrations.AddField(
            model_name='template',
            name='category',
            field=models.CharField(blank=True, help_text='Category (e.g., USDT, Special Price, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for text fields (auto-generated by editor)'),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Rename background to image and update upload path
        migrations.RenameField(
            model_name='template',
            old_name='background',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(help_text='Background image for the template', upload_to='templates/'),
        ),
        # Make name unique
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Unique name for this template', max_length=100, unique=True),
        ),
        # Note: We keep Element model for backward compatibility, but new system uses JSONField
    ]

