# Generated by Django 5.2.7 on 2025-11-24 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template_editor', '0002_redesign_template_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Element',
        ),
    ]
