# Generated by Django 5.2.7 on 2025-11-24 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_pricetype_unique_category_pair_trade'),
        ('special_price', '0001_initial'),
        ('template_editor', '0003_delete_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='special_price_type',
            field=models.ForeignKey(blank=True, help_text='Special price type this template belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='special_price.specialpricetype'),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this template belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
    ]
