# Generated by Django 6.1 on 2026-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_editor', '0010_remove_marquee_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='plan',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=16),
        ),
    ]
