# Generated by Django 6.1 on 2026-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_editor', '0011_template_plan_alter_widget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('clock', 'Clock'), ('date', 'Date'), ('weekday', 'Weekday'), ('countdown', 'Countdown'), ('text', 'Text'), ('weather', 'Weather'), ('qr_action', 'QR action'), ('image', 'Image'), ('video', 'Video'), ('album', 'Album'), ('webview', 'Webview'), ('chart', 'Chart')], default='text', max_length=40),
        ),
    ]
