# Generated by Django 6.1 on 2026-09-05 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_customuser_account'),
        ('category', '0013_category_account_alter_category_name_and_more'),
        ('template_editor', '0012_alter_widget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(help_text='Name for this template, unique within the account', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='uniq_template_name_per_account'),
        ),
    ]
