# Generated by Django 6.1 on 2026-09-05 18:15

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

from accounts.bootstrap import backfill_account


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_customuser_account'),
        ('template_editor', '0013_template_account_alter_template_name_and_more'),
    ]

    operations = [
        migrations.RunPython(
            backfill_account('template_editor.Template'), migrations.RunPython.noop, elidable=True
        ),
        migrations.AlterModelManagers(
            name='template',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='template',
            name='account',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account'),
        ),
    ]
