# Generated by Django 6.1 on 2026-09-05 18:18

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template_editor', '0014_alter_template_managers_alter_template_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, help_text='Background image for the template (optional; editor can use solid color only)', null=True, upload_to=accounts.storage.AccountUploadPath('templates')),
        ),
    ]
