# Generated by Django 5.0.1 on 2026-02-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_submission_ack_telegram_username'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adrequest',
            new_name='core_adrequ_status_9babbe_idx',
            old_name='core_adrequ_status_8a0c0d_idx',
        ),
        migrations.RenameIndex(
            model_name='adrequest',
            new_name='core_adrequ_created_d788b8_idx',
            old_name='core_adrequ_created_9b0e1f_idx',
        ),
        migrations.RenameIndex(
            model_name='adrequest',
            new_name='core_adrequ_categor_8516f7_idx',
            old_name='core_adrequ_categor_7d2a3b_idx',
        ),
    ]
