# Generated by Django 5.0.1 on 2026-02-03 19:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_link_adrequest_to_telegramuser'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='telegrammessagelog',
            new_name='core_telegr_bot_id_4c49f3_idx',
            old_name='core_telegr_bot_id_9babbe_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramsession',
            new_name='core_telegr_telegra_88801f_idx',
            old_name='core_telegr_telegra_9babbe_idx',
        ),
        migrations.RenameIndex(
            model_name='telegramsession',
            new_name='core_telegr_state_2d6721_idx',
            old_name='core_telegr_state_9babbe_idx',
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='telegramsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='telegramsession',
            name='state',
            field=models.CharField(choices=[('START', 'Start'), ('SELECT_LANGUAGE', 'Select Language'), ('ASK_CONTACT', 'Ask Contact'), ('CHOOSE_CONTACT_TYPE', 'Choose Contact Type'), ('ENTER_PHONE', 'Enter Phone'), ('ENTER_EMAIL', 'Enter Email'), ('MAIN_MENU', 'Main Menu'), ('ENTER_CONTENT', 'Enter Content'), ('SELECT_CATEGORY', 'Select Category'), ('CONFIRM', 'Confirm'), ('SUBMITTED', 'Submitted'), ('EDITING', 'Editing')], db_index=True, default='START', max_length=32),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
