# Generated by Django 5.0.1 on 2026-02-06 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_telegr_bot_id_9babbe_idx_core_telegr_bot_id_4c49f3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client identifier', max_length=128)),
                ('api_key_hashed', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_per_min', models.PositiveIntegerField(default=60, help_text='Max requests per minute')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstagramConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Instagram account username', max_length=128)),
                ('access_token_encrypted', models.TextField(blank=True)),
                ('page_id', models.CharField(blank=True, help_text='Facebook Page ID linked to Instagram', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instagram Configuration',
                'verbose_name_plural': 'Instagram Configurations',
            },
        ),
        migrations.AlterField(
            model_name='telegramsession',
            name='state',
            field=models.CharField(choices=[('START', 'Start'), ('SELECT_LANGUAGE', 'Select Language'), ('ASK_CONTACT', 'Ask Contact'), ('CHOOSE_CONTACT_TYPE', 'Choose Contact Type'), ('ENTER_PHONE', 'Enter Phone'), ('ENTER_EMAIL', 'Enter Email'), ('MAIN_MENU', 'Main Menu'), ('ENTER_CONTENT', 'Enter Content'), ('SELECT_CATEGORY', 'Select Category'), ('CONFIRM', 'Confirm'), ('SUBMITTED', 'Submitted'), ('EDITING', 'Editing'), ('RESUBMIT_EDIT', 'Resubmit Edit'), ('RESUBMIT_CONFIRM', 'Resubmit Confirm')], db_index=True, default='START', max_length=32),
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('api', 'API')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='core.adrequest')),
            ],
            options={
                'verbose_name': 'Delivery Log',
                'verbose_name_plural': 'Delivery Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ad', 'channel'], name='core_delive_ad_id_96833a_idx'), models.Index(fields=['status'], name='core_delive_status_c47d8b_idx')],
            },
        ),
    ]
