# Generated by Django 5.0.1 on 2026-02-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delivery_instagram_api_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramconfiguration',
            name='ig_user_id',
            field=models.CharField(blank=True, help_text='Instagram Graph API user ID', max_length=64),
        ),
        migrations.AddField(
            model_name='instagramconfiguration',
            name='placeholder_image_url',
            field=models.URLField(blank=True, help_text='Default image for caption-only ads'),
        ),
    ]
