# Generated by Django 5.0.1 on 2026-02-06 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_instagram_placeholder_ig_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adrequest',
            name='submitted_via_api_client',
            field=models.ForeignKey(blank=True, help_text='If set, ad was submitted via Partner API by this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_ads', to='core.apiclient'),
        ),
    ]
