# Generated by Django 5.0.1 on 2026-02-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_adrequest_submitted_via_api_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='mode',
            field=models.CharField(choices=[('webhook', 'Webhook'), ('polling', 'Polling')], default='polling', help_text='Webhook: updates via HTTP. Polling: runbots worker fetches getUpdates.', max_length=16),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='requested_action',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('stop', 'Stop'), ('restart', 'Restart')], help_text='Start/Stop/Restart requested by admin; runbots applies it.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='worker_pid',
            field=models.PositiveIntegerField(blank=True, help_text='PID of polling worker when running', null=True),
        ),
        migrations.AddField(
            model_name='telegrambot',
            name='worker_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
