# Generated by Django 5.0.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_telegram_bot_polling_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last error message; cleared on success'),
        ),
    ]
