# Generated by Django 5.2.9 on 2026-02-07 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_telegrambot_last_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='approval_message_template',
            field=models.TextField(default='🎉 Your ad has been approved! Thank you for using Iraniu. 🙏', help_text='Sent to user on approval. Use {ad_id} only if you need it (not shown by default).'),
        ),
        migrations.AlterField(
            model_name='telegramsession',
            name='state',
            field=models.CharField(choices=[('START', 'Start'), ('SELECT_LANGUAGE', 'Select Language'), ('ASK_CONTACT', 'Ask Contact'), ('CHOOSE_CONTACT_TYPE', 'Choose Contact Type'), ('ENTER_PHONE', 'Enter Phone'), ('ENTER_EMAIL', 'Enter Email'), ('MAIN_MENU', 'Main Menu'), ('MY_ADS', 'My Ads'), ('ENTER_CONTENT', 'Enter Content'), ('SELECT_CATEGORY', 'Select Category'), ('CONFIRM', 'Confirm'), ('SUBMITTED', 'Submitted'), ('EDITING', 'Editing'), ('RESUBMIT_EDIT', 'Resubmit Edit'), ('RESUBMIT_CONFIRM', 'Resubmit Confirm')], db_index=True, default='START', max_length=32),
        ),
        migrations.CreateModel(
            name='ScheduledInstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Public URL of image for posting', max_length=2048)),
                ('caption', models.TextField(help_text='Caption (message, email, phone). Max 2200 chars.')),
                ('message_text', models.TextField(blank=True, help_text='Original message text')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When to publish')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('instagram_media_id', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_instagram_posts', to='core.adrequest')),
            ],
            options={
                'verbose_name': 'Scheduled Instagram Post',
                'verbose_name_plural': 'Scheduled Instagram Posts',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='core_schedu_status_39d1bc_idx')],
            },
        ),
    ]
