# Generated by Django 5.0.1 on 2026-02-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_category_model'),
        ('core', '0018_force_iraniu_ads_bot_webhook'),
    ]

    operations = [
    ]
