# Generated by Django 5.0.1 on 2026-02-08 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20260208_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='webhook_secret_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Secret UUID in webhook path; only Telegram and this app know the URL.', unique=True),
        ),
    ]
