# Generated by Django 5.0.1 on 2026-02-08 12:58
# Fixed: run rename only if old index exists (avoids "no such index" when DB state differs).

from django.db import migrations


def _index_exists(cursor, name):
    cursor.execute(
        "SELECT 1 FROM sqlite_master WHERE type='index' AND name=%s",
        [name],
    )
    return cursor.fetchone() is not None


def safe_rename_index_forward(apps, schema_editor):
    """Rename index only if old exists; otherwise ensure new index exists."""
    with schema_editor.connection.cursor() as cursor:
        old_name = "core_adrequ_categor_8516f7_idx"
        new_name = "core_adrequ_categor_e52f17_idx"
        table = "core_adrequest"
        if _index_exists(cursor, old_name):
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "{new_name}" ON "{table}" ("category_id", "status")'
            )
            cursor.execute(f'DROP INDEX IF EXISTS "{old_name}"')
        elif not _index_exists(cursor, new_name):
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "{new_name}" ON "{table}" ("category_id", "status")'
            )


def safe_rename_index_reverse(apps, schema_editor):
    """Reverse: rename back only if new index exists."""
    with schema_editor.connection.cursor() as cursor:
        old_name = "core_adrequ_categor_8516f7_idx"
        new_name = "core_adrequ_categor_e52f17_idx"
        table = "core_adrequest"
        if _index_exists(cursor, new_name):
            cursor.execute(
                f'CREATE INDEX IF NOT EXISTS "{old_name}" ON "{table}" ("category_id", "status")'
            )
            cursor.execute(f'DROP INDEX IF EXISTS "{new_name}"')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_core_adrequ_categor_8516f7_idx_core_adrequ_categor_e52f17_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='adrequest',
                    new_name='core_adrequ_categor_e52f17_idx',
                    old_name='core_adrequ_categor_8516f7_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(safe_rename_index_forward, safe_rename_index_reverse),
            ],
        ),
    ]
