# Generated by Django 5.2.9 on 2026-02-08 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_core_adrequ_categor_8516f7_idx_core_adrequ_categor_e52f17_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(blank=True, help_text='Telegram chat ID to receive new-request notifications (numeric).', max_length=32)),
                ('is_notified', models.BooleanField(default=True, help_text='When True, this admin receives Telegram notifications for new requests.')),
                ('admin_nickname', models.CharField(blank=True, help_text='Optional display name for this admin (e.g. for lists).', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
