# Generated by Django (add Start/Stop runbots control from UI)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_admin_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambot",
            name="current_pid",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="PID of the runbots supervisor process when started from UI (for Stop).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="telegrambot",
            name="is_running",
            field=models.BooleanField(
                default=False,
                help_text="True when a runbots process for this bot was started from the panel.",
            ),
        ),
    ]
