# Generated by Django 5.2.9 on 2026-02-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_telegrambot_current_pid_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='facebook_access_token_encrypted',
            field=models.TextField(blank=True, help_text='Long-lived Facebook/Instagram access token (encrypted at rest).'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instagram_business_id',
            field=models.CharField(blank=True, help_text='Instagram Graph API user ID (Business account linked to Facebook Page).', max_length=64),
        ),
    ]
