# Generated by Django 5.2.9 on 2026-02-10 15:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_instagram_site_config_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=128)),
                ('background_image', models.ImageField(help_text='Background image for the ad', upload_to='ad_templates/backgrounds/')),
                ('font_file', models.FileField(blank=True, help_text='TrueType font (.ttf) for text overlay', null=True, upload_to='ad_templates/fonts/')),
                ('category_x_pos', models.IntegerField(default=50, help_text='X position (pixels)')),
                ('category_y_pos', models.IntegerField(default=50)),
                ('category_font_size', models.IntegerField(default=48)),
                ('category_text_color', models.CharField(default='#FFFFFF', help_text='Hex color (e.g. #FFFFFF)', max_length=9)),
                ('category_max_width', models.IntegerField(default=800, help_text='Max width for text wrapping (0 = no wrap)')),
                ('ad_text_x_pos', models.IntegerField(default=50)),
                ('ad_text_y_pos', models.IntegerField(default=120)),
                ('ad_text_font_size', models.IntegerField(default=32)),
                ('ad_text_text_color', models.CharField(default='#FFFFFF', max_length=9)),
                ('ad_text_max_width', models.IntegerField(default=800)),
                ('phone_x_pos', models.IntegerField(default=50)),
                ('phone_y_pos', models.IntegerField(default=400)),
                ('phone_font_size', models.IntegerField(default=28)),
                ('phone_text_color', models.CharField(default='#FFFF00', max_length=9)),
                ('phone_max_width', models.IntegerField(default=400)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ad Template',
                'verbose_name_plural': 'Ad Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for this channel (e.g. "Main Ads Channel")', max_length=128)),
                ('channel_id', models.CharField(help_text='Telegram Chat ID (e.g. -100123456789 for supergroups)', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='When disabled, this channel is excluded from automated posts.')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Primary channel for automated ads. Only one channel can be default.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot_connection', models.ForeignKey(help_text='Bot that has admin rights in this channel (used to send messages).', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channels', to='core.telegrambot')),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Channel Manager',
                'ordering': ['title'],
            },
        ),
    ]
