# Generated by Django 5.2.9 on 2026-02-10 15:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_telegram_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adtemplate',
            options={'ordering': ['name'], 'verbose_name': 'Ad Template', 'verbose_name_plural': 'Template Manager'},
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='ad_text_font_size',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='ad_text_max_width',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='ad_text_text_color',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='ad_text_x_pos',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='ad_text_y_pos',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='category_font_size',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='category_max_width',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='category_text_color',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='category_x_pos',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='category_y_pos',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='phone_font_size',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='phone_max_width',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='phone_text_color',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='phone_x_pos',
        ),
        migrations.RemoveField(
            model_name='adtemplate',
            name='phone_y_pos',
        ),
        migrations.AddField(
            model_name='adtemplate',
            name='coordinates',
            field=models.JSONField(blank=True, default=core.models.default_adtemplate_coordinates, help_text='JSON with keys: category, description, phone. Each contains x, y, size, color, font_path; description also has max_width.'),
        ),
        migrations.AddField(
            model_name='adtemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active templates are eligible for auto-selection.'),
        ),
        migrations.AlterField(
            model_name='adtemplate',
            name='font_file',
            field=models.FileField(blank=True, help_text='Default TrueType font (.ttf) for text overlay', null=True, upload_to='ad_templates/fonts/'),
        ),
    ]
