# Generated by Django 5.2.9 on 2026-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_adtemplate_coordinates_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEV', 'Development')], db_index=True, default='PROD', help_text='PROD: cPanel/live. DEV: local/testing. Only bots matching settings.ENVIRONMENT are started.', max_length=8),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='name',
            field=models.CharField(help_text='Human-readable name (e.g. Production Bot, Dev Bot)', max_length=128),
        ),
    ]
