# Generated by Django 5.2.9 on 2026-02-11 11:51

import django.db.models.deletion
from django.db import migrations, models


def link_existing_channels_to_site_config(apps, schema_editor):
    """Attach existing TelegramChannels to the singleton Site Configuration (pk=1)."""
    SiteConfiguration = apps.get_model("core", "SiteConfiguration")
    TelegramChannel = apps.get_model("core", "TelegramChannel")
    if not SiteConfiguration.objects.filter(pk=1).exists():
        return
    TelegramChannel.objects.filter(site_config__isnull=True).update(site_config_id=1)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_dev_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_telegram_bot',
            field=models.ForeignKey(blank=True, help_text='Bot used to post to the default channel above (must have admin rights in that channel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.telegrambot'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='is_channel_active',
            field=models.BooleanField(default=False, help_text='When True, approved ads are posted to the channel above using the bot below.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='telegram_channel_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID for the default ads channel (e.g. -100123456789).', max_length=32),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='telegram_channel_title',
            field=models.CharField(blank=True, help_text='Display name for the default channel (e.g. "Live Ads Channel").', max_length=128),
        ),
        migrations.AddField(
            model_name='telegramchannel',
            name='site_config',
            field=models.ForeignKey(blank=True, help_text='Link to Site Configuration to manage this channel from Settings.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channels', to='core.siteconfiguration'),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='Primary channel for automated ads (when not using Site Configuration default).'),
        ),
        migrations.RunPython(link_existing_channels_to_site_config, noop),
    ]
