# Generated by Django 5.2.9 on 2026-02-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_site_config_telegram_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', help_text='Global UI theme: Light (easy on eyes) or Dark.', max_length=16),
        ),
    ]
