# Generated by Django 5.0.1 on 2026-02-11 17:58

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_theme_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'permissions': (('can_edit_settings', 'Can edit restricted CRM settings tabs'),), 'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configuration'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='auto_reply_comments',
            field=models.BooleanField(default=False, help_text='Enable automatic replies to comments.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='auto_reply_dms',
            field=models.BooleanField(default=False, help_text='Enable automatic replies to DMs.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='auto_responder_message',
            field=models.TextField(blank=True, default='Welcome to Iraniu. Please send your ad details to continue.', help_text='Automatic welcome message sent when a user starts the bot.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_font',
            field=models.CharField(blank=True, default='', help_text='Default font for generated content and UI defaults (path/name).', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_watermark_opacity',
            field=models.PositiveSmallIntegerField(default=60, help_text='Default watermark opacity percentage (0-100).'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='retention_policy',
            field=models.CharField(choices=[('1w', '1 Week'), ('1m', '1 Month'), ('forever', 'Forever')], default='1m', help_text='How long generated images are retained.', max_length=16),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='workflow_stages',
            field=models.JSONField(blank=True, default=core.models.default_workflow_stages, help_text='Ordered workflow stages: [{"key","label","enabled"}].'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('object_type', models.CharField(blank=True, default='', max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_activi_created_5c6490_idx'), models.Index(fields=['object_type'], name='core_activi_object__1953f3_idx')],
            },
        ),
    ]
