# Generated by Django 5.0.1 on 2026-02-11 18:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_systemstatus_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtemplate',
            name='coordinates',
            field=models.JSONField(blank=True, default=core.models.default_adtemplate_coordinates, help_text='JSON with keys: category, description, phone, price. Each contains x, y, size, color, font_path, align; description also has max_width.'),
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='active_errors',
            field=models.JSONField(blank=True, default=core.models.default_active_errors, help_text='List of current error messages, e.g. ["Instagram Token Expired"].'),
        ),
    ]
