# Generated by Django 5.0.1 on 2026-02-12 13:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_seed_main_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtemplate',
            name='coordinates',
            field=models.JSONField(blank=True, default=core.models.default_adtemplate_coordinates, help_text='JSON with keys: category, description, phone. Each contains x, y, size, color, font_path, align, bold; description also has max_width.'),
        ),
    ]
