# Generated by Django 5.2.9 on 2026-02-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_adtemplate_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='telegram_channel_handle',
            field=models.CharField(blank=True, help_text='Channel handle shown in captions (e.g. @YourChannel).', max_length=64),
        ),
    ]
