# Generated by Django 5.2.9 on 2026-02-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_channel_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='cleanup_retention_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days to keep generated images before manual cleanup (min 1).'),
        ),
    ]
