# Generated by Django 5.2.9 on 2026-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_cleanup_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='is_instagram_enabled',
            field=models.BooleanField(default=False, help_text='Auto-managed: True when all required Instagram fields are filled.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='facebook_access_token_encrypted',
            field=models.TextField(blank=True, default='', help_text='Long-lived Facebook/Instagram access token (encrypted at rest).', null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='instagram_app_id',
            field=models.CharField(blank=True, default='', help_text='Facebook App ID (Meta for Developers).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='instagram_app_secret_encrypted',
            field=models.TextField(blank=True, default='', help_text='Facebook App Secret (encrypted at rest).', null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='instagram_business_id',
            field=models.CharField(blank=True, default='', help_text='Instagram Graph API user ID (Business account linked to Facebook Page).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='instagram_oauth_state',
            field=models.CharField(blank=True, default='', help_text='CSRF state token for in-progress Instagram OAuth flow.', max_length=128, null=True),
        ),
    ]
