from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _


class Layer(models.Model):
    """Editor layer (PixelCast-style); default layer holds synced widgets."""

    template = models.ForeignKey(
        "Template",
        related_name="editor_layers",
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=120, default="Default Layer")
    order = models.PositiveSmallIntegerField(default=0)
    width = models.PositiveIntegerField(null=True, blank=True)
    height = models.PositiveIntegerField(null=True, blank=True)

    class Meta:
        ordering = ["template_id", "order", "id"]
        constraints = [
            models.UniqueConstraint(
                fields=["template", "name"],
                name="template_editor_layer_unique_name_per_template",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.template_id}:{self.name}"


class Widget(models.Model):
    """Widget row synced from Template.config_json.widgets."""

    WIDGET_TYPE_CHOICES = [
        ("clock", _("Clock")),
        ("date", _("Date")),
        ("weekday", _("Weekday")),
        ("countdown", _("Countdown")),
        ("text", _("Text")),
        ("weather", _("Weather")),
        ("qr_action", _("QR action")),
        ("image", _("Image")),
        ("video", _("Video")),
        ("album", _("Album")),
        ("webview", _("Webview")),
        ("chart", _("Chart")),
    ]

    layer = models.ForeignKey(
        Layer,
        related_name="widgets",
        on_delete=models.CASCADE,
    )
    widget_uuid = models.UUIDField(unique=True, editable=False)
    type = models.CharField(max_length=40, choices=WIDGET_TYPE_CHOICES, default="text")
    name = models.CharField(max_length=200, blank=True)
    content = models.TextField(blank=True)
    content_url = models.URLField(max_length=2000, blank=True)
    content_json = models.JSONField(default=dict, blank=True)
    x_pct = models.CharField(max_length=32, blank=True)
    y_pct = models.CharField(max_length=32, blank=True)
    w_pct = models.CharField(max_length=32, blank=True)
    h_pct = models.CharField(max_length=32, blank=True)
    z_index = models.IntegerField(default=0)
    rotation = models.FloatField(default=0)
    is_active = models.BooleanField(default=True)

    class Meta:
        ordering = ["layer_id", "z_index", "id"]

    def __str__(self) -> str:
        return f"{self.widget_uuid}:{self.type}"


class Template(models.Model):
    """Template model with JSONField for storing text field configurations."""
    
    name = models.CharField(
        max_length=100,
        unique=True,
        help_text="Unique name for this template"
    )
    category = models.ForeignKey(
        'category.Category',
        on_delete=models.CASCADE,
        help_text="Category this template belongs to."
    )
    image = models.ImageField(
        upload_to="templates/",
        null=True,
        blank=True,
        help_text="Background image for the template (optional; editor can use solid color only)",
    )
    config = models.JSONField(
        default=dict,
        blank=True,
        help_text="JSON configuration for text fields (auto-generated by editor)"
    )
    config_json = models.JSONField(
        default=dict,
        blank=True,
        help_text="PixelCast-style layout: widgets, backgroundColor, etc.",
    )
    canvas_width = models.PositiveIntegerField(
        default=1920,
        help_text="Design canvas width in pixels (logical)",
    )
    canvas_height = models.PositiveIntegerField(
        default=1080,
        help_text="Design canvas height in pixels (logical)",
    )
    orientation = models.CharField(
        max_length=20,
        default="landscape",
        choices=[("landscape", _("Landscape")), ("portrait", _("Portrait"))],
    )
    is_active = models.BooleanField(
        default=True,
        help_text=_("If false, excluded from round-robin publishing for this category/special."),
    )
    publish_order = models.PositiveSmallIntegerField(
        default=0,
        help_text=_("Lower values are used first in round-robin order within the same category."),
    )
    telegram_caption_template = models.TextField(
        blank=True,
        help_text=_(
            "Optional HTML caption for Telegram when this template is used. "
            "Placeholders: {date_fa}, {pair_name}, {price__slug}, etc. from dynamic data."
        ),
    )
    telegram_buttons_json = models.JSONField(
        default=list,
        blank=True,
        help_text=_('Inline keyboard rows, e.g. [[{"text": "…", "url": "https://…"}]].'),
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Template"
        verbose_name_plural = "Templates"
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.name

    def clean(self):
        """Validate template uniqueness and category-scoped price bindings."""
        super().clean()
        if self.name:
            # Check for duplicate names excluding current instance
            qs = Template.objects.filter(name=self.name)
            if self.pk:
                qs = qs.exclude(pk=self.pk)
            if qs.exists():
                raise ValidationError({"name": _("A template with this name already exists.")})
        
        if not self.category_id:
            raise ValidationError({"category": _("Template category is required.")})

        if self.pk:
            invalid_binding_ids = list(
                self.price_bindings.exclude(price_type__category_id=self.category_id).values_list(
                    "price_type_id", flat=True
                )
            )
            if invalid_binding_ids:
                raise ValidationError(
                    {
                        "price_bindings": _(
                            "All template price bindings must belong to the same category as template."
                        )
                    }
                )

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)


class TemplateWidgetBinding(models.Model):
    """Stable contract between a widget slot and a category PriceType."""

    template = models.ForeignKey(
        Template,
        related_name="price_bindings",
        on_delete=models.CASCADE,
    )
    widget_uuid = models.UUIDField()
    price_type = models.ForeignKey(
        "category.PriceType",
        related_name="template_bindings",
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["template_id", "id"]
        constraints = [
            models.UniqueConstraint(
                fields=["template", "widget_uuid"],
                name="template_widget_binding_unique_widget_per_template",
            ),
        ]

    def clean(self):
        super().clean()
        if self.template_id and self.price_type_id:
            if self.price_type.category_id != self.template.category_id:
                raise ValidationError(
                    {
                        "price_type": _(
                            "Price type must belong to the same category as template."
                        )
                    }
                )

    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

