"""
Iraniu — Core URL routes.
"""

from django.urls import path
from . import views
from . import telegram_views
from . import views_api_v1

urlpatterns = [
    path('', views.landing, name='landing'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/channels/', views.channel_list, name='channel_list'),
    path('dashboard/channels/create/', views.channel_create, name='channel_create'),
    path('dashboard/channels/<int:pk>/delete/', views.channel_delete, name='channel_delete'),
    path('dashboard/channels/<int:pk>/set-default/', views.channel_set_default, name='channel_set_default'),
    path('dashboard/channels/<int:pk>/test/', views.channel_test_connection, name='channel_test_connection'),
    path('requests/', views.ad_list, name='ad_list'),
    path('requests/bulk-reject/', views.bulk_reject_page, name='bulk_reject_page'),
    path('requests/<uuid:uuid>/', views.ad_detail, name='ad_detail'),
    path('request/<uuid:uuid>/', views.request_detail, name='request_detail'),
    path('requests/<uuid:uuid>/approve/', views.confirm_approve, name='confirm_approve'),
    path('requests/<uuid:uuid>/reject/', views.confirm_reject, name='confirm_reject'),
    path('requests/<uuid:uuid>/request-revision/', views.confirm_request_revision, name='confirm_request_revision'),
    path('requests/<uuid:uuid>/preview-publish/', views.preview_publish, name='preview_publish'),
    path('requests/<uuid:uuid>/post-to-instagram/<str:target>/', views.post_to_instagram_view, name='post_to_instagram'),
    path('bots/', views.bot_list, name='bot_list'),
    path('bots/create/', views.bot_create, name='bot_create'),
    path('bots/<int:pk>/edit/', views.bot_edit, name='bot_edit'),
    path('bots/<int:pk>/delete/', views.bot_delete, name='bot_delete'),
    path('bots/<int:pk>/test/', views.bot_test, name='bot_test'),
    path('bots/<int:pk>/update-token/', views.bot_update_default_token, name='bot_update_default_token'),
    path('bots/<int:pk>/sync-webhook/', views.bot_sync_webhook, name='bot_sync_webhook'),
    path('bots/<int:pk>/reset-connection/', views.bot_reset_connection, name='bot_reset_connection'),
    path('bots/<int:pk>/regenerate-webhook/', views.bot_regenerate_webhook, name='bot_regenerate_webhook'),
    path('bots/<int:pk>/start/', views.bot_start, name='bot_start'),
    path('bots/<int:pk>/stop/', views.bot_stop, name='bot_stop'),
    path('bots/<int:pk>/restart/', views.bot_restart, name='bot_restart'),
    path('bots/<int:bot_id>/toggle/', views.toggle_bot_status, name='toggle_bot_status'),
    path('settings/', views.settings_hub_redirect, name='settings'),
    path('settings/hub/instagram/', views.settings_hub_section, {'section': 'instagram'}, name='settings_hub_instagram'),
    path('settings/hub/telegram/', views.settings_hub_section, {'section': 'telegram'}, name='settings_hub_telegram'),
    path('settings/hub/channels/', views.settings_hub_section, {'section': 'channels'}, name='settings_hub_channels'),
    path('settings/hub/design/', views.settings_hub_section, {'section': 'design'}, name='settings_hub_design'),
    path('settings/hub/storage/', views.settings_hub_section, {'section': 'storage'}, name='settings_hub_storage'),
    path('settings/check-instagram/', views.check_instagram_connection, name='check_instagram_connection'),
    path('settings/hub/instagram/connect/', views.instagram_connect, name='instagram_oauth_connect'),
    path('settings/hub/instagram/callback/', views.instagram_callback, name='instagram_oauth_callback'),
    path('settings/hub/instagram/check-permissions/', views.instagram_check_permissions, name='instagram_check_permissions'),
    path('notifications/<int:pk>/read/', views.notification_mark_read, name='notification_mark_read'),
    path('notifications/read-all/', views.notification_mark_all_read, name='notification_mark_all_read'),
    path('categories/', views.category_list, name='categories'),
    path('categories/add/', views.category_create, name='category_create'),
    path('categories/<int:pk>/edit/', views.category_edit, name='category_edit'),
    path('categories/<int:pk>/toggle/', views.category_toggle, name='category_toggle'),
    path('categories/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('admin-management/', views.admin_management_list, name='admin_management_list'),
    path('admin-management/create/', views.admin_management_create, name='admin_management_create'),
    path('admin-management/<int:pk>/edit/', views.admin_management_edit, name='admin_management_edit'),
    path('admin-management/<int:pk>/test-notification/', views.admin_test_notification, name='admin_test_notification'),
    path('settings/save/', views.settings_save, name='settings_save'),
    path('settings/invite-member/', views.settings_invite_member, name='settings_invite_member'),
    path('settings/change-password/', views.settings_change_password, name='settings_change_password'),
    path('settings/theme/', views.theme_save, name='theme_save'),
    path('settings/test-telegram/', views.test_telegram, name='test_telegram'),
    path('settings/test-openai/', views.test_openai, name='test_openai'),
    path('settings/export/', views.export_config, name='export_config'),
    path('settings/export-ads-csv/', views.export_ads_csv, name='export_ads_csv'),
    path('settings/export-users-excel/', views.export_users_excel, name='export_users_excel'),
    path('settings/import/', views.import_config, name='import_config'),
    path('settings/cleanup-media/', views.cleanup_generated_media, name='cleanup_generated_media'),
    path('settings/reset-all/', views.reset_all_settings, name='reset_all_settings'),
    path('settings/instagram/', views.settings_instagram, name='settings_instagram'),
    path('settings/instagram/create/', views.settings_instagram_edit, name='settings_instagram_create'),
    path('settings/instagram/<int:pk>/edit/', views.settings_instagram_edit, name='settings_instagram_edit'),
    path('settings/instagram/<int:pk>/test/', views.settings_instagram_test, name='settings_instagram_test'),
    path('settings/api/', views.settings_api, name='settings_api'),
    path('settings/api/key-display/', views.settings_api_key_display, name='settings_api_key_display'),
    path('settings/api/create/', views.settings_api_edit, name='settings_api_create'),
    path('settings/api/<int:pk>/edit/', views.settings_api_edit, name='settings_api_edit'),
    # Ad templates: create, manual editor, and tester
    path('templates/create/', views.template_create, name='template_create'),
    path('templates/<int:template_id>/edit-coordinates/', views.template_manual_edit, name='template_manual_edit'),
    path('templates/tester/', views.template_tester, name='template_tester'),
    path('templates/tester/preview/', views.template_tester_preview, name='template_tester_preview'),
    path('deliveries/', views.delivery_list, name='delivery_list'),
    path('deliveries/<int:pk>/retry/', views.delivery_retry, name='delivery_retry'),
    path('api/instagram/post/', views.api_instagram_post, name='api_instagram_post'),
    path('api/approve/', views.approve_ad, name='approve_ad'),
    path('api/reject/', views.reject_ad, name='reject_ad'),
    path('api/bulk-approve/', views.bulk_approve, name='bulk_approve'),
    path('api/bulk-reject/', views.bulk_reject, name='bulk_reject'),
    path('api/pulse/', views.api_pulse, name='api_pulse'),
    path('api/submit/', views.submit_ad, name='submit_ad'),
    path('api/v1/submit/', views_api_v1.api_v1_submit, name='api_v1_submit'),
    path('api/v1/status/<uuid:uuid>/', views_api_v1.api_v1_status, name='api_v1_status'),
    path('api/v1/list/', views_api_v1.api_v1_list, name='api_v1_list'),
    path('telegram/webhook/<int:bot_id>/', telegram_views.telegram_webhook, name='telegram_webhook'),
    path('telegram/webhook/<uuid:webhook_secret_token>/', views.TelegramWebhookView.as_view(), name='telegram_webhook_by_token'),
]
