# Generated by Django 5.2.7 on 2025-11-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_remove_pricetype_unique_category_pair_trade'),
        ('special_price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('template_type', models.CharField(choices=[('default', 'Default'), ('category', 'Category'), ('special', 'Special Price')], default='default', max_length=20)),
                ('background_image', models.ImageField(help_text='Background used for the rendered price image.', upload_to='price_templates/backgrounds/')),
                ('logo_image', models.ImageField(blank=True, help_text='Logo positioned on the rendered image (optional).', null=True, upload_to='price_templates/logos/')),
                ('watermark_image', models.ImageField(blank=True, help_text='Watermark placed near the bottom of the rendered image (optional).', null=True, upload_to='price_templates/watermarks/')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_template', to='category.category')),
                ('special_price_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_template', to='special_price.specialpricetype')),
            ],
            options={
                'verbose_name': 'Price Template',
                'verbose_name_plural': 'Price Templates',
                'ordering': ['name'],
            },
        ),
    ]
