# Generated by Django 6.1 on 2026-09-05 18:18

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_publisher', '0004_alter_pricetemplate_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetemplate',
            name='background_image',
            field=models.ImageField(help_text='Background used for the rendered price image.', upload_to=accounts.storage.AccountUploadPath('price_templates/backgrounds')),
        ),
        migrations.AlterField(
            model_name='pricetemplate',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Logo positioned on the rendered image (optional).', null=True, upload_to=accounts.storage.AccountUploadPath('price_templates/logos')),
        ),
        migrations.AlterField(
            model_name='pricetemplate',
            name='watermark_image',
            field=models.ImageField(blank=True, help_text='Watermark placed near the bottom of the rendered image (optional).', null=True, upload_to=accounts.storage.AccountUploadPath('price_templates/watermarks')),
        ),
    ]
