# Generated by Django 5.2.7 on 2025-11-05 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_remove_pricetype_unique_category_pair_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_price_types_source', to='category.currency')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_price_types_target', to='category.currency')),
            ],
            options={
                'verbose_name': 'Special Price Type',
                'verbose_name_plural': 'Special Price Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('special_price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_price_histories', to='special_price.specialpricetype')),
            ],
            options={
                'verbose_name': 'Special Price History',
                'verbose_name_plural': 'Special Price Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
