# Generated by Django 5.2.9 on 2026-04-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_repair_last_used_template_column'),
        ('special_price', '0002_add_icon_to_specialpricetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPricePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_price_pairs_source', to='category.currency')),
                ('special_price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='special_price.specialpricetype')),
                ('target_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='special_price_pairs_target', to='category.currency')),
            ],
            options={
                'verbose_name': 'Special Price Pair',
                'verbose_name_plural': 'Special Price Pairs',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='specialpricehistory',
            name='pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='special_price.specialpricepair'),
        ),
        migrations.AddConstraint(
            model_name='specialpricepair',
            constraint=models.UniqueConstraint(fields=('special_price_type', 'source_currency', 'target_currency'), name='uniq_special_price_pair_per_type'),
        ),
    ]
