# Generated by Django 5.2.9 on 2026-04-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_repair_last_used_template_column'),
        ('special_price', '0004_backfill_pairs_and_require_history_pair'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='specialpricepair',
            name='uniq_special_price_pair_per_type',
        ),
        migrations.AddField(
            model_name='specialpricepair',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='specialpricepair',
            constraint=models.UniqueConstraint(fields=('special_price_type', 'source_currency', 'target_currency', 'trade_type'), name='uniq_special_price_pair_per_type'),
        ),
    ]
