# Generated by Django 5.2.9 on 2026-04-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_price', '0005_remove_specialpricepair_uniq_special_price_pair_per_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialpricepair',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
