# Generated by Django 5.2.9 on 2026-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_price', '0008_specialpricetype_last_used_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialpricehistory',
            name='event_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
