# Generated by Django 6.1 on 2026-09-05 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_customuser_account'),
        ('category', '0013_category_account_alter_category_name_and_more'),
        ('special_price', '0009_add_event_at_to_price_histories'),
        ('template_editor', '0013_template_account_alter_template_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialpricetype',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='specialpricetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='specialpricetype',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='specialpricetype',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='uniq_spt_name_per_account'),
        ),
        migrations.AddConstraint(
            model_name='specialpricetype',
            constraint=models.UniqueConstraint(fields=('account', 'slug'), name='uniq_spt_slug_per_account'),
        ),
    ]
